routes/web.php
<?php

use App\Models\Request;
use Illuminate\Support\Str;
use App\Helpers\RequestLogger;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Config;

use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\ActorController;

Route::get('/', function () {
    return view('welcome');
});


//Route::get('/.well-known/webfinger?resource={webfinger}', function () {
//	Log::debug(request());
//});

if (str_contains(request()->url(), "/livewire") == false && request()->header('User-Agent') != "Symfony") {
    Log::info(request()->url());
    Log::info(request()->method());
    Log::info(request()->header('Accept'));
    Log::info(request()->header('Content-Type'));
    Log::info(request()->header('User-Agent'));
    Log::info(request()->all());
}

Route::get('/u/' . env('LOCAL_ACTOR_USERNAME', 'jack'), [ActorController::class, 'profile']);

Route::get('/.well-known/webfinger', function () {
    $array = [
        "subject" => "acct:" . env('LOCAL_ACTOR_USERNAME', 'jack') . "@" . request()->getHost() . "",
        "aliases" => [
            "https://" . request()->getHost() . "/web/u/" . env('LOCAL_ACTOR_USERNAME', 'jack') . "",
            "https://" . request()->getHost() . "/u/" . env('LOCAL_ACTOR_USERNAME', 'jack') . ""
        ],
        "links" => [
            [
                "rel" => "http://webfinger.net/rel/profile-page",
                "type" => "text/html",
                "href" => "https://" . request()->getHost() . "/web/u/" . env('LOCAL_ACTOR_USERNAME', 'jack') . ""
            ],
            [
                "rel" => "self",
                "type" => "application/activity+json",
                "href" => "https://" . request()->getHost() . "/u/" . env('LOCAL_ACTOR_USERNAME', 'jack') . ""
            ],
            [
                "rel" => "http://ostatus.org/schema/1.0/subscribe",
                "template" => "https://" . request()->getHost() . "/authorize_interaction?uri={uri}"
            ]
        ]
    ];
    RequestLogger::log($array);

    return response($array, 200);
});
Route::get('/.well-known/host-meta', function () {
    echo 'as';
    RequestLogger::log("webfinger host meta");
    return response('', 200);
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/', function () {
        return view('sender');
    })->name('sender');
    Route::get('/flow', function () {
        return view('flow');
    })->name('flow');
});

Route::post('u/' . env('LOCAL_ACTOR_USERNAME', 'jack') . '/inbox', function () {
    RequestLogger::log(env('LOCAL_ACTOR_USERNAME', 'jack') . " inbox");
    return response(env('LOCAL_ACTOR_USERNAME', 'jack') . ' inbox', 200);
});

Route::any('{any}', function ($any) {
    RequestLogger::log("route /{$any} not found sorry...");
    return "route not found sorry...";
});

app/Models/Request.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Request extends Model
{
    use HasFactory;

    protected $casts = [
        'respHeaders' => 'array',
        'respBody' => 'array',
        'body' => 'array',
        'headers' => 'array',
    ];

    protected $fillable = [
        'type',
        'method',
        'url',
        'userAgent',
        'ip',
        'status',
        'headers',
        'respHeaders',
        'body',
        'respBody'
    ];

    public function getPrettyJsonBodyAttribute()
    {
        return json_encode($this->body, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }

    public function getPrettyJsonBodyRespAttribute()
    {
        $respBody = $this->respBody;
        if ($respBody != null) {
            if (is_array($respBody) == false) {
                $respBody = json_decode($respBody, true);
                if ($respBody == null) {
                    return $this->respBody;   //if not an array a not a JSON parsable string, this is just a string, so just return it.
                }
            }
            return json_encode($respBody, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }
        return $respBody;
    }

    public function getSourceAttribute()
    {
        //Try to extract the source form the User-Agent. Ex: " http.rb/5.0.4 (Mastodon/3.5.1; +https://indieweb.social/)"
        $userAgent = $this->userAgent;
        $url = Str::substr($this->userAgent, strpos($userAgent, '+'));   //extract URL
        //$domain = Str::substr($source, strpos($source, "https://") + 8, strlen($source) - 8 - 2);
        $domain = Str::before(Str::after($url, '//'), '/');
        if ($domain == "" || preg_match("/[a-z]{3,}\.[a-z]{2,}/", $domain) !== 1) {
            if ($this->ip == null) {
                return $userAgent;
            } else {
                return $this->ip;
            }
        }
        return $domain;
    }

    public function getDestinationAttribute()
    {
        return Str::before(Str::after($this->url, '//'), '/');
    }
}

app/Http/Livewire/ApFlow.php
<?php

namespace App\Http\Livewire;

use App\Models\Request;
use Livewire\Component;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class ApFlow extends Component
{
    public $requests;

    public function render()
    {
        $this->requests = Request::all()->append(['prettyJsonBody', 'prettyJsonBodyResp']);
        $this->requests->map(function (Request $request) {

            $fields = ['respHeaders', 'headers'];

            foreach ($fields as $field) {
                if ($request->{$field} != null) {
                    $request->{$field} = Arr::where($request->{$field}, function ($value, $key) {
                        return is_array($value) ? trim($value[0]) != "" : trim($value) != "";
                    });
                }
            }

            return $request;
        });
        $this->dispatchBrowserEvent('highlight');
        return view('livewire.ap-flow');
    }

    public function trashRequests()
    {
        DB::table('requests')->truncate();
        $this->requests = [];
    }
}

app/Http/Livewire/ApSender.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Str;
use App\Helpers\HttpSignature;
use App\Helpers\RequestLogger;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class ApSender extends Component
{
    public $activityId;
    public $objectId;
    public $actorUsername;
    public $actorWebfinger = "";
    public $signed = false;
    public $recipient;
    public $recipientProfile;
    public $properties;
    public $responseBody;
    public $responseCode = '?';
    public $discoverError = "";
    public $sendError = "";
    public $sentRequest = null;

    protected $listeners = ['addALineTo'];

    public function mount()
    {
        $this->recipient = env('DEFAULT_SENDER_RECIPIENT', '');
        $this->actorUsername = env('LOCAL_ACTOR_USERNAME', 'jack');

        $props = [
            //id, actor, and to will be automatically generated for finalProps.
            [
                "key" => "type",
                "value" => "Create",
                "readonly" => false
            ], [
                "key" => "to",
                "value" => "https://mas.to/users/rick",
                "readonly" => false
            ], [
                "key" => "object",
                "value" => [
                    //id, attributedTo, and to will be automatically generated for finalProps.
                    [
                        "key" => "type",
                        "value" => "Note",
                        "readonly" => false
                    ], [
                        "key" => "content",
                        "value" => "Hello Rick !!",
                        "readonly" => false
                    ],
                    [
                        "key" => "",
                        "value" => null,
                        "readonly" => false
                    ]
                ],
                "readonly" => false
            ]
        ];
        $this->properties = collect($props);

        $this->actorWebfinger = "@" . $this->actorUsername . "@" . request()->getHost();
    }

    public function getFinalPropertiesProperty()
    {
        //Build the dynamic properties
        $this->activityId = Str::random(10);
        $this->objectId = Str::random(10);

        $props = [];
        $props['@context'] = "https://www.w3.org/ns/activitystreams";
        $props['id'] = "https://" . request()->getHost() . "/activities/" . $this->activityId;
        $props = array_merge($props, $this->mixKeyValues($this->properties));
        $props['actor'] = $this->getActorURI();
        $props['published'] = now();

        $newProps = $props;

        //Dynamic properties if the object exists and is an array
        if (isset($props['object']) && is_array($props['object'])) {
            $object = $props['object'];
            unset($props['object']);
            $props['object']['id'] = "https://" . request()->getHost() . "/objects/" . $this->objectId;
            $props['object'] = array_merge($props['object'], $object);
            $props['object']['attributedTo'] = $this->getActorURI();
            $props['object']['published'] = $props['published'];
            $props['object']['to'] = $props['to'];


            //Remove empty props at sublevel (in the 'object' array)
            //TODO: refactor to have all levels and not only objects
            unset($newProps['object']);
            foreach ($props['object'] as $key => $prop) {
                if (trim($key) != "") {
                    $newProps['object'][trim($key)] = $prop == "" ? null : $prop;
                }
            }
        }

        //Remove empty props at first level
        foreach ($newProps as $key => $prop) {
            if (trim($key) != "") {
                $finalProps[trim($key)] = $prop == "" ? null : $prop;
            }
        }

        return $finalProps;
    }

    public function getPrettyFinalPropertiesProperty()
    {
        $props = $this->finalProperties;
        return json_encode($props, (JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    }

    public function mixKeyValues($properties)
    {
        $mixedCollection = [];
        foreach ($properties as $prop) {
            if (is_array($prop['value'])) {
                $prop['value'] = $this->mixKeyValues($prop['value']);
            }
            $mixedCollection[$prop['key']] = $prop['value'];
        }
        return $mixedCollection;
    }

    public function render()
    {
        $this->dispatchBrowserEvent('highlight');
        return view('livewire.ap-sender');
    }

    public function addALineTo($field)
    {
        //Todo: add line addition for sub JSON objects
        //Todo: algo: remove last dot char and look for the path with the dot notation.
        $this->properties->push([
            "key" => "",
            "value" => "",
            "readonly" => false
        ]);
    }

    public function resolve()
    {
        //Get Webfinger data
        $recipientId = null;
        $this->discoverError = "";
        $webfinger = $this->recipient;
        $domainPieces = explode("@", $webfinger);
        $domain = $domainPieces[count($domainPieces) - 1];
        if (Str::startsWith($webfinger, "@")) {
            $webfinger = Str::substr($webfinger, 1);
        }
        $webfingerUrl = "https://" . $domain . "/.well-known/webfinger?resource=acct:" . $webfinger;

        try {
            $responseWebfinger = Http::accept("application/ld+json")->get($webfingerUrl);
            RequestLogger::saveRequestWith($responseWebfinger, $webfingerUrl);
            $webfingerData = collect(json_decode($responseWebfinger->body()));
            foreach ($webfingerData['links'] as $link) {
                if (in_array($link->type, ["application/activity+json", "application/ld+json"])) {
                    $recipientId = $link->href;
                    break;
                }
            }

            //Get recipient profile
            try {
                if ($recipientId != null) {
                    $responseProfile = Http::accept("application/ld+json")->get($recipientId);
                    RequestLogger::saveRequestWith($responseProfile, $recipientId);
                    if ($responseProfile->successful() == false) {
                        $this->discoverError = $responseProfile->clientError();
                    }
                    $this->recipientProfile = json_decode($responseProfile->body(), true);
                }
            } catch (ModelNotFoundException $e) {
                $this->discoverError .=  " " . $e->getMessage();
            }
        } catch (ModelNotFoundException $e) {
            $this->discoverError = " " . $e->getMessage();
        }
    }

    public function getActorURI()
    {
        return "https://" . request()->getHost() . "/u/" . $this->actorUsername;
    }

    public function send()
    {
        $this->sentRequest = null;
        if ($this->recipientProfile != null) {
            $this->sendError = "";

            //Build required info
            $key = Storage::get('private.pem');
            $keyId = $this->getActorURI() . "#main-key";
            $url = $this->getRecipientInbox();
            $data = $this->finalProperties;

            if ($this->signed) {
                $headers = HttpSignature::sign($key, $keyId, $url, $data);
            } else {
                $headers = [];
            }

            $response = Http::withHeaders($headers)->post($url, $data);
            $this->sentRequest = RequestLogger::saveRequestWith($response, $url, 'POST', $data, $headers);
            $this->responseBody = $response->body();
            $this->responseCode = $response->status();
        } else {
            $this->sendError = "No actor loaded. Discover one first.";
        }
    }

    public function getRecipientInbox()
    {
        return $this->recipientProfile['inbox'] ?? null;
    }
}

resources/views/livewire/ap-flow.blade.php
<div>
    <div class="my-3 bg-blue-100 shadow-md" wire:poll.2s="$refresh()">
        <div class="flex" x-data="{ req: null, displayHeaders: false }">
            <div class="p-2 lg:pr-10 sm:pr-5 pr-2">
                <div class="flex">
                    <div class="flex-1 flex items-center">
                        <h2 class="text-xl">Requests inspection</h2>
                        <span class="ml-5">{{ $requests->count() }} requests</span>
                    </div>
                    <div>
                        <button class="btn py-0" wire:click="trashRequests" @click="req = null">Trash</button>
                    </div>
                </div>

                <hr class="my-1 border-t border-cblue">

                <div class="py-1 flex-1 max-h-[73vh] overflow-scroll">
                    @forelse ($requests as $request)
                        <div :class="req == null || req != {{ $request->id }} ? '' : '!bg-orange-300'"
                            class="bg-orange-200 hover:bg-orange-300 rounded p-2 h-min mb-2 relative shadow-lg border border-orange-400 {{ $request->type == 'out' ? 'mr-0' : 'ml-0' }} cursor-pointer max-w-lg"
                            @click="req = {{ $request->id }}">
                            <div class="flex items-center">
                                <span class="font-semibold mr-2  md:text-lg">{{ strtoupper($request->type) }}</span>
                                <div class="flex-1">

                                    <span class="mr-2 italic whitespace-nowrap flex items-center">
                                        {{ request()->getHost() }}
                                        <div class="mx-2">
                                            @if ($request->type == 'in')
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none"
                                                    viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                        d="M7 16l-4-4m0 0l4-4m-4 4h18" />
                                                </svg>
                                            @else
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none"
                                                    viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                        d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                                </svg>
                                            @endif
                                        </div>
                                        {{ $request->type == 'in' ? $request->source : $request->destination }}
                                    </span>
                                </div>
                                <div class="text-sm w-max flex items-center">
                                    <div
                                        class="flex items-center justify-center font-semibold h-7 w-7 border border-orange-400">
                                        {{ $request->id }}
                                    </div>
                                </div>
                            </div>


                            <div class="text-xs md:text-sm lg:text-base">
                                <span class=" font-semibold mr-1">{{ $request->method }}</span>
                                <span class="text-url break-all">{{ $request->url }}</span>
                            </div>
                            <div class="flex">
                                <div class="flex flex-1">
                                    @if ($request->status != null)
                                        <div class="text-sm md:text-base mr-2 label">
                                            Status:
                                            {{ $request->status }}</div>
                                    @endif

                                    @if ($request->method == 'POST' && isset($request->body['type']))
                                        <div class="text-sm md:text-base mr-2 label">
                                            Activity type: {{ $request->body['type'] }}
                                        </div>
                                    @endif

                                </div>
                                <div class="w-max mr-2 text-xs my-1">{{ $request->created_at->diffForHumans() }}
                                </div>

                            </div>
                        </div>
                    @empty
                        <span class="text-info">No request for the moment</span>
                    @endforelse
                </div>
            </div>

            <!-- Details panel at the right -->
            <div x-show="req != null" x-cloak class="w-full max-w-full overflow-hidden">
                <div class="max-w-full flex-1 w-full bg-blue-200 md:p-2 py-2 px-1 h-full" x-show="req != null">
                    <div class="flex mb-2">
                        <h2 class="flex-1 text-xl">Details inspection</h2>
                        <div class="flex items-center justify-center font-semibold h-7 w-7 bg-orange-500">
                            @foreach ($requests as $request)
                                <div :hidden="req != {{ $request->id }}">
                                    {{ $request->id }}
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="mb-2">
                        @foreach ($requests as $request)
                            <div :hidden="req != {{ $request->id }}">
                                <span class="font-semibold">{{ $request->method }}</span>
                                <span class="text-url break-all">{{ $request->url }}</span>
                            </div>
                        @endforeach
                    </div>
                    <hr class=" mb-1 border-t border-cblue">

                    <div class="w-full max-h-[73vh] xl:flex overflow-hidden">

                        {{-- Body zones --}}
                        <div class="xl:w-[60%] overflow-scroll">
                            {{-- Request body displayed only when the method is not GET --}}
                            @foreach ($requests as $request)
                                @if ($request->method != 'GET')
                                    <div class="min-w-full mb-2" :hidden="req != {{ $request->id }}">

                                        <h3 class="flex-1 text-lg">Request body</h3>

                                        <div class="text-sm w-full overflow-hidden">
                                            @if ($request->body != null)
                                                <x-code type="json" x-cloak>
                                                    {{ $request->prettyJsonBody }}</x-code>
                                            @else
                                                <div class="italic text-gray-100 p-2 bg-dark rounded mr-2">no body sent
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                @endif
                            @endforeach

                            {{-- Response body --}}
                            <div class="min-w-full mb-2 max-w-full ">
                                <div class="flex">
                                    <h3 class="flex-1 text-lg">Response body</h3>
                                </div>
                                @foreach ($requests as $request)
                                    <div class="text-sm w-full overflow-hidden overflow-x-scroll"
                                        :hidden="req != {{ $request->id }}">
                                        @if ($request->respBody != null)
                                            <x-code type="json" x-cloak>{{ $request->prettyJsonBodyResp }}
                                            </x-code>
                                        @else
                                            <div class="italic text-gray-100 p-2 bg-dark rounded mr-2">no body received
                                            </div>
                                        @endif
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        {{-- Headers zones --}}
                        <div class="xl:w-[40%] overflow-scroll">
                            <div class="text-lg">Headers</div>
                            <div>

                                {{-- Request headers --}}
                                <div>
                                    <div class="min-w-full mb-2">
                                        <div class="flex">
                                            <h3 class="flex-1 text-base">Requests headers</h3>
                                        </div>
                                        <div
                                            class="text-sm bg-gray-100 p-2 rounded overflow-hidden break-all max-w-full">
                                            @foreach ($requests as $request)
                                                <div :hidden="req != {{ $request->id }}">
                                                    @if ($request->headers != null)
                                                        @foreach ($request->headers as $index => $header)
                                                            <div>
                                                                @if (Arr::isAssoc($request->headers))
                                                                    <span
                                                                        class="font-extrabold">{{ $index }}</span>:
                                                                @endif
                                                                <span class="text-gray-700">{{ $header }}</span>
                                                            </div>
                                                        @endforeach
                                                    @else
                                                        <div class="text-info">no logged headers</div>
                                                    @endif
                                                </div>
                                            @endforeach
                                        </div>

                                    </div>
                                </div>

                                {{-- Response headers --}}
                                <div class="min-w-full mb-2">
                                    <div class="flex">
                                        <h3 class="flex-1 text-base">Response headers</h3>
                                    </div>
                                    <div class="text-sm w-full overflow-hidden bg-gray-100 rounded p-2">
                                        @foreach ($requests as $request)
                                            <div :hidden="req != {{ $request->id }}">
                                                @if ($request->respHeaders != null)
                                                    @foreach ($request->respHeaders as $index => $header)
                                                        <div>
                                                            @if (Arr::isAssoc($request->respHeaders))
                                                                <span
                                                                    class="font-extrabold">{{ $index }}</span>:
                                                            @endif
                                                            <span
                                                                class="text-gray-700">{{ is_array($header) ? $header[0] : $header }}</span>
                                                        </div>
                                                    @endforeach
                                                @else
                                                    <div class="text-info">no logged response headers</div>
                                                @endif
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>